apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
      project: roboshop
      environment: dev
      tier: backend
      components: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      components: cart
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        components: cart
    spec:
      containers:
      - name: cart
        image: akkimahesh/cart:v1
        resources:
          requests:
            memory: "50Mi"
            cpu: "150m"
          limits:
            memory: "100Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2 #if the probe fails 2 times, the container will be restarted
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15 #wait for 15 seconds before checking the health
          periodSeconds: 3 #every 3 seconds check the health
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
      project: roboshop
      environment: dev
      tier: backend
      components: cart
  ports:
    - protocol: TCP
      port: 8080  #service port
      targetPort: 8080 #container port
